### PR TITLE
Feature/login GitHub

### PR DESCRIPTION
**Pull request by Marchabar**
For the github login to work you need the following:

We need to install social auth, then:
```
pip install -r requirements.txt
``` 
```
python decide/manage.py makemigrations
python decide/manage.py migrate
```
In your .env add the following (ask Marchabar for the values of the variables and do not share them):
```
GITHUB_KEY=github_key_Marchabar
GITHUB_SECRET=github_secret_Marchabar
```
If you did all of this correctly, it should work.
The GitHub login button is in the login page under the google login.

### CODE REVIEW

**Comment by Marchabar** [comment]
Hey, I need 2 of you to check this pr please.

**Comment by MartaInes** [comment]
> Hey, I need 2 of you to check this pr please.

I can do it

**Comment by auroranavas** [comment]
> Hey, I need 2 of you to check this pr please.

I can take care of it as well

**Review by auroranavas — APPROVED** [review]
Tests pass correctly and the GitHub log-in works. Great job!

**Review by MartaInes — APPROVED** [review]
It works perfectly!

**Pull request merged**
