### PR TITLE
fix(mixnet): Incorrect if statement in mixnet

### PR DESCRIPTION
**Pull request by pabpercab1**
An if statement in the mixnet module was causing some tests to fail. Now it's fixed and the tests should run properly again. This was probably because the msg parameter was only allowed to be 2 or 3 as length.

Disclaimer: I have assigned this PR to @auroranavas and @marnunrey2 because most of Zambrano-2 was busy.

### CODE REVIEW

**Review by auroranavas — APPROVED** [review]

**Review by JaviGarc1a — CHANGES_REQUESTED** [review]
Error appeared in line 164 (if len(msgs2[0]) == 3:)

**Comment by pabpercab1** [comment]
> Error appeared in line 164 (if len(msgs2[0]) == 3:)

Can you send the complete error message with the test that is failing?

**Comment by JaviGarc1a** [comment]
Test with error is test_white_vote_is_false_tally. [Here](https://github.com/EGC-zambrano/decide-part-zambrano/actions/runs/7260984281/job/19781252943) you can see the trace.

**Comment by pabpercab1** [comment]
We identified an occasional issue where the test 'test_white_vote_is_false_tally' doesn't execute correctly within the vote module. This anomaly arises due to the recent implementation of the mixnet module aimed at facilitating the priority voting feature. The irregularity occurs when the mixnet module is invoked for shuffling or decrypting, and the list of votes happens to be empty.

While this issue can be resolved, the required resolution demands more time than presently available. It's important to note that this doesn't impact any functionalities within the Decide app. Therefore, we've made the decision to close this pull request. Should the team find themselves with additional time in the future, we will consider reopening it for further investigation and resolution. Thank you for your understanding and cooperation.

**Pull request closed without merging**
