### PR TITLE
Feature/reopen votings

### PR DESCRIPTION
**Pull request by FelixoGudiel**
Closed votings can now be reopened. This will reset the end_date attribute, giving voters that didn't previously vote in it a chance to do so now. Both Unit Test and Selenium tests have been added.

### CODE REVIEW

**Comment by FelixoGudiel** [comment]
> The functionality works correctly but the selenium test fails. Change paths to self.live_server_url

This has already been tried, but for the selenium process it is not that simple. If you ask the system to output the port selenium is working, the port is not correct and does not correlate to self.live_server_url. I ve found that it is fixed by manually changing the port the app uses to 8000.

**Review by JMGarCas — CHANGES_REQUESTED** [review]
The feature is not working as expected. While you can reopen a voting, once is closed and the tally is performed, the previous votes related to that voting are lost and only the newest votes are taking into account when performing the tally.

Captura desde 2023-11-15 11-18-34

Here you can see 3 votes in the db, the first one is the newest one.

Captura desde 2023-11-15 11-17-32

Here is the results after all the calculations. Only one is taking into account, which is the first one.

**Comment by FelixoGudiel** [comment]
Okay, I have now fixed the selenium test so that anybody can try it out without changing the port and fixed the tally issue, now when a voting is reopened all previous votes are discarded, that way when you reopen a voting you also give the users that voted previously the chance to change minds. Thank you for your feedback

**Review by JaviGarc1a — APPROVED** [review]
Good job! Works well. Merge from development and resolve conflict if any.

**Comment by JMGarCas** [comment]
> Okay, I have now fixed the selenium test so that anybody can try it out without changing the port and fixed the tally issue, now when a voting is reopened all previous votes are discarded, that way when you reopen a voting you also give the users that voted previously the chance to change minds. Thank you for your feedback

People can change their votes if a voting is open. With your approach, If a person has already voted before and he does not realize that the voting has been reopened, this person will loose his or her vote. Therefore, it is not necessary to delete any of the votes from the database. You have to make sure that the tally takes into account all the votes related to the voting, regardless of whether it has been reopened or not. Please revert this change and correct the functionality.

**Comment by FelixoGudiel** [comment]
Okay, following your recommendation, instead of resetting the votes, the tally will recount all of them. If you find any other problem, do tell me.

**Review by JMGarCas — APPROVED** [review]
Now it works, good job!

**Review by JaviGarc1a — APPROVED** [review]

**Pull request merged**
